In [1]:
import numpy as np

# Basic arrays
a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.ones((3, 3))
d = np.eye(3)  # Identity matrix
e = np.arange(0, 10, 2)
f = np.linspace(0, 1, 5)

print("Array a:", a)
print("Zeros b:\n", b)
print("Ones c:\n", c)
print("Identity d:\n", d)
print("Arange e:", e)
print("Linspace f:", f)

# Type conversion
g = a.astype(float)
print("Converted to float:", g)

Array a: [1 2 3]
Zeros b:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones c:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity d:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange e: [0 2 4 6 8]
Linspace f: [0.   0.25 0.5  0.75 1.  ]
Converted to float: [1. 2. 3.]


In [2]:
arr = np.arange(10)
print("Original:", arr)

# Fancy indexing
print("Even index values:", arr[[0, 2, 4, 6]])

# Boolean indexing
print("Values > 5:", arr[arr > 5])

# Conditional replacement
arr[arr < 5] = -1
print("Replaced arr:", arr)

Original: [0 1 2 3 4 5 6 7 8 9]
Even index values: [0 2 4 6]
Values > 5: [6 7 8 9]
Replaced arr: [-1 -1 -1 -1 -1  5  6  7  8  9]


In [3]:
x = np.array([1, 2, 3])
y = np.array([[10], [20], [30]])

# Broadcasting addition
result = x + y
print("Broadcasted addition:\n", result)

# Vectorized operation instead of loop
z = np.arange(1, 6)
squared = z ** 2
print("Squared values:", squared)

Broadcasted addition:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Squared values: [ 1  4  9 16 25]


In [4]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Element-wise operations
print("Element-wise addition:\n", mat1 + mat2)
print("Matrix multiplication:\n", np.dot(mat1, mat2))  # or mat1 @ mat2

# Element-wise math functions
a = np.array([1, 4, 9])
print("Sqrt:", np.sqrt(a))
print("Exp:", np.exp(a))
print("Log:", np.log(a))

Element-wise addition:
 [[ 6  8]
 [10 12]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Sqrt: [1. 2. 3.]
Exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03]
Log: [0.         1.38629436 2.19722458]


In [5]:
data = np.random.randn(3, 4)
print("Data:\n", data)

print("Mean:", np.mean(data))
print("Mean across columns:", np.mean(data, axis=0))
print("Std deviation:", np.std(data))
print("Percentile (50th):", np.percentile(data, 50))

Data:
 [[-0.1477125   0.58612105 -1.01856384  1.04138627]
 [ 0.65972647 -0.78035573 -0.39067742 -1.61700188]
 [-2.04072934  0.11204201 -1.4603361  -0.15906346]]
Mean: -0.43459703967500457
Mean across columns: [-0.50957179 -0.02739756 -0.95652579 -0.24489302]
Std deviation: 0.9294868590834612
Percentile (50th): -0.2748704419787955


In [6]:
x = np.arange(12)
reshaped = x.reshape((3, 4))
print("Reshaped:\n", reshaped)

# Flatten
print("Flattened:", reshaped.flatten())

# Transpose
print("Transposed:\n", reshaped.T)

# Stack arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Vertical stack:\n", np.vstack((a, b)))
print("Horizontal stack:", np.hstack((a, b)))

Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]


In [7]:
np.random.seed(42)  # Reproducibility

# Random floats
print("Random rand:", np.random.rand(3))

# Normal distribution
print("Random randn:", np.random.randn(3))

# Random integers
print("Random ints:", np.random.randint(0, 10, size=5))

# Shuffle array
x = np.arange(10)
np.random.shuffle(x)
print("Shuffled:", x)

# Random choice
print("Random choice:", np.random.choice(x, size=3, replace=False))

Random rand: [0.37454012 0.95071431 0.73199394]
Random randn: [-1.11188012  0.31890218  0.27904129]
Random ints: [7 2 5 4 1]
Shuffled: [8 2 9 6 0 4 3 1 5 7]
Random choice: [7 4 3]


In [8]:
# Simulate a dataset
X = np.random.randn(1000, 2)  # 1000 samples, 2 features
y = np.random.choice([0, 1], size=1000)

# Normalize X manually
X_min = X.min(axis=0)
X_max = X.max(axis=0)
X_norm = (X - X_min) / (X_max - X_min)

# Compute Euclidean distance between two samples
from numpy.linalg import norm
dist = norm(X[0] - X[1])
print("Distance between sample 0 and 1:", dist)

# Class-wise mean
print("Mean of class 0:", X[y == 0].mean(axis=0))
print("Mean of class 1:", X[y == 1].mean(axis=0))

Distance between sample 0 and 1: 1.7802728645265071
Mean of class 0: [ 0.00153865 -0.02498835]
Mean of class 1: [0.10760501 0.06378004]
